### ISSUE TITLE
Trakt integration

### ISSUE THREAD

**Issue by ironicnet** [popcorn-time/popcorn-time.github.io#10]
It would be great to have some kind of integration with Trakt. Or allow us a way to include plugins or scripts to do it.

**Comment by ironicnet** [comment]
I  Don't know how to tag it as a feature request

**Comment by caiodias** [comment]
Maybe you can tag as improvement.

On Tuesday, March 4, 2014, Ezequiel Calderara notifications@github.com
wrote:

> I Don't know how to tag it as a feature request
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/popcorn-time/popcorn-time.github.io/issues/10#issuecomment-36698608
> .

## 

Caio Dias
https://about.me/caiodias

**Comment by ironicnet** [comment]
I think that his should be in the app and not in the website rep. 

Sorry for the confussion.
