### ISSUE TITLE
Wrong link for downloading linux version

### ISSUE THREAD

**Issue by SamyPesse** [popcorn-time/popcorn-time.github.io#11]
The top link for downloading the app on linux system is linking to the windows executable.

**Comment by AndreaGiardini** [comment]
I confirm this issue

**Comment by heyimjuani** [comment]
@SamyPesse @AndreaGiardini thanks for reporting this guys, it's now fixed!

**Comment by AndreaGiardini** [comment]
Lol You are too fast man! :D
