### ISSUE TITLE
Translation of the page

### ISSUE THREAD

**Issue by EvandroZanatta** [popcorn-time/popcorn-time.github.io#17]
The question of translating the site for different languages ​​can be discussed? 

I find interesting since the app is well globalized in different languages​​. The site should accompany this positive point. 

create pages with address $path/pt, $path/es, $path/pt-br would be something easy to implement.

**Comment by remil19** [comment]
I already added a pull request where translations are generated once and then are just some static files. Using JS could easily redirect the user to the correct language. The Turkish has just been added.

**Comment by EvandroZanatta** [comment]
I understand, already marked this issue as a "pull request", I will close this isssue
