### ISSUE TITLE
Fonts do not support Czech language

### ISSUE THREAD

**Issue by pavelbinar** [popcorn-time/popcorn-time.github.io#36]
Hi guys,
I made an fork for czech version of your site: https://github.com/pavelbinar/popcorntime.cz/tree/czech

and find out that used font "BrandonText" do not support some czech characters like: `č, ů` and so on.

Would you consider using different font with brother language support?
Or do you have this font in another version supporting more language characters?

Thanks!

**Comment by remil19** [comment]
We made modifications to be able to translate the site easily at https://github.com/remil19/popcorn-time.github.io, there is already five languages available and waiting to be pulled in the main repository. It may be useful to add your work in it. The issue you are reporting has been also spotted with Greek and Turkish.

**Comment by pavelbinar** [comment]
Hi, thanks for info. I will put it into:  https://github.com/remil19/popcorn-time.github.io
Just curious - why it is not in main repository?: https://github.com/popcorn-time/popcorn-time.github.io

**Comment by remil19** [comment]
I really do not know. You should be aware that i am not a part of the main team so i don't when my changes will  be merged in the main repository (if they are one day). The main team did not respond to our questions until now...

Actually there is more and more issues on this repository and it seems like the main team never respond...

**Comment by pavelbinar** [comment]
I would not be so hard on the core team. I guess they are under big pressure to do a lot of stuff and the website in another languages is probably not the priority right now.

**Comment by remil19** [comment]
And yet there has been a lot of commits for the website and a Spanish translation.

**Comment by EvandroZanatta** [comment]
I think we should have a team focused only on site. The App supports 31 languages​​. Currently the site supports 2.

**Comment by remil19** [comment]
Totally but i cannot spend anymore time on this. I already spent too much time on this and won't be able to spend anymore. Maintaining translations won't be very difficult : commit the new language, run php generate-static.php, done.
