### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by alevizio** [popcorn-time/popcorn-time.github.io#4]
Just as a remainder we should add some warning message saying that torrents may be ilegal in your country, what do you think?

**Comment by heyimjuani** [comment]
_Popcorn Hour streams movies from torrents_
Downloading copyrighted material through torrents may be illegal in your country. Use at your own risk.

**Comment by alevizio** [comment]
Looking like this :dancer: 
![screenshot 2014-02-25 11 18 24](https://f.cloud.github.com/assets/3001854/2258364/c640094a-9e27-11e3-8749-39c31dc1c53a.png)
