### ISSUE TITLE
MEGA download link is down

### ISSUE THREAD

**Issue by achikin** [popcorn-time/popcorn-time.github.io#42]
https://mega.co.nz/#!RZBDQY4J!KhIzQ-74Dz5s8_ntNxhNWHD3Qwj6a8mdfHf8w4p6AYY

**Comment by neuromancer** [comment]
The file you are trying to download is no longer available. This could be due to the following reasons:
- The file has been removed because of a ToS/AUP violation.
- Invalid URL - the link you are trying to access does not exist
- The file has been deleted by the user.

**Comment by Rockyfelle** [comment]
Works now
